version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /volume1/docker/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3001:3001
    restart: always
    labels:
      # proxy settings
      - "traefik.enable=true"    
      - "traefik.http.routers.uptimekuma.entrypoints=https"
      - "traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.uptimekuma.tls=true"
      - "traefik.http.routers.uptimekuma.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.uptimekuma.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.uptimekuma.tls.domains[0].sans=*.${LOCAL_DOMAIN}"
      # homepage integration
      - homepage.group=Monitoring
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma.png
      - homepage.href=https://uptimekuma.${LOCAL_DOMAIN}
      - homepage.description=Uptime monitor
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=http://uptime-kuma:3001
      - homepage.widget.slug=services
      # auto update docker
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true