version: '3'
services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /volume1/docker/tautulli:/config
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kyiv
    ports:
      - 8181:8181
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true
