services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${VOLUME_DATA}/ollama:/root/.ollama
    labels:
      # auto update docker
      - "com.centurylinklabs.watchtower.enable=true"
  proxy:
    image: ghcr.io/jmorganca/ollama-openai-proxy:latest
    container_name: ollama_proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    labels:
      # auto update docker
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    name: containers_bridge
    external: true