version: "3.8"
services:
  grafana:
    image: alhazmy13/telegraf-influxdb-grafana:latest
    container_name: grafana
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/config/grafana:/var/lib/grafana
      - /volume1/config/influxdb:/var/lib/influxdb
    ports:
      - 49155:22/tcp
      - 3003:3003/tcp
      - 5144:514/udp
      - 49154:8086/tcp
      - 49153:8125/udp
      - 49153:8888/tcp
    restart: unless-stopped
networks:
  default:
    name: containers_bridge
    external: true