version: '3'
services:
  grafana:
    image: alhazmy13/telegraf-influxdb-grafana:latest
    container_name: grafana
    environment:
      - TZ=Europe/Kiev
    restart: unless-stopped
    volumes:
      - /volume1/docker/grafana_new:/var/lib/grafana
      - /volume1/docker/influxdb:/var/lib/influxdb
    ports:
      - 3003:3003
      - 5144:514/udp
      - 8086:8086
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
networks:
  default:
    name: containers_bridge
    external: true