version: '3'
services:
  grafana:
    image: alhazmy13/telegraf-influxdb-grafana:latest
    container_name: grafana
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    restart: unless-stopped
    volumes:
      - /volume1/config/grafana:/var/lib/grafana
      - /volume1/config/influxdb:/var/lib/influxdb
    ports:
      - 3003:3003
      - 5144:514/udp
networks:
  default:
    name: containers_bridge
    external: true