version: '2'
services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    environment:
      TZ: 'Europe/Kyiv'
    volumes:
      - /volume1/docker/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"