version: "3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1026
      - USER_GID=100
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
      - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY}
      - GITEA__security__INTERNAL_TOKEN=${GITEA_INTERNAL_TOKEN} 
    restart: unless-stopped
    volumes:
      - /volume1/docker/gitea/server:/data
    ports:
      - "3030:3000"
      - "222:22"
    depends_on:
      - db
    labels:
      # proxy settings      
      - "traefik.enable=true"    
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.rule=Host(`gitea.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.gitea.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.gitea.tls.domains[0].sans=*.${LOCAL_DOMAIN}"
      # homepage integration      
      - homepage.group=Development
      - homepage.name=Gitea
      - homepage.icon=gitea.png
      - homepage.href=https://gitea.${LOCAL_DOMAIN}
      - homepage.description=Self-hosted Git repo
      - homepage.widget.type=gitea
      - homepage.widget.url=http://gitea:3000
      - homepage.widget.key=${GITEA_API_TOKEN}
      # auto update docker        
      - "com.centurylinklabs.watchtower.enable=true"    

  db:
    image: postgres:14
    container_name: gitea-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${GITEA_DB_USER}
      - POSTGRES_PASSWORD=${GITEA_DB_PASSWORD}
      - POSTGRES_DB=${GITEA_DB_NAME}
    volumes:
      - /volume1/docker/gitea/db:/var/lib/postgresql/data      

networks:
  default:
    name: containers_bridge
    external: true      