version: "3"

services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    volumes:
      - "/volume1/config/gotify/data:/app/data"
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify-local.rule=Host(`gotify.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.gotify-local.entrypoints=https"
      - "traefik.http.routers.gotify-local.tls=true"
      - "traefik.http.routers.gotify-local.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.gotify-local.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.gotify-local.tls.domains[0].sans=*.${LOCAL_DOMAIN}"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true