version: "3"

services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    volumes:
      - "/volume1/config/gotify/data:/app/data"
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
    networks:
      macvlan:
        ipv4_address: 192.168.1.10        
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`${TRAEFIK_GOTIFY}`)"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.routers.gotify.tls.certresolver=mydnschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    name: containers_bridge
    external: true
  macvlan:
    name: macvlan
    driver: macvlan
    driver_opts:
      parent: ovs_bond0
    ipam:
      config:
        - subnet: 192.168.1.1/24
          ip_range: 192.168.1.10/31
          gateway: 192.168.1.1