version: "3.2"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    mem_limit: 512m
    cpu_shares: 512
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health
    ports:
      - 3340:3000
    volumes:
      - /volume1/docker/synology-monitoring/grafana:/var/lib/grafana:rw
    environment:
      TZ: Europe/Kiev
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,natel-discrete-panel,grafana-piechart-panel
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  prometheus:
    image: prom/prometheus
    command:
      - '--storage.tsdb.retention.time=60d'
      - '--config.file=/etc/prometheus/prometheus.yml'
    container_name: prometheus
    ports:
    - 9090:9090
    hostname: prometheus
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges=true
    user: 1026:100
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/ || exit 1
    volumes:
      - /volume1/docker/synology-monitoring/prometheus:/prometheus:rw
      - /volume1/docker/synology-monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - --collector.disable-defaults
      - --collector.stat
      - --collector.time
      - --collector.cpu
      - --collector.loadavg
      - --collector.hwmon
      - --collector.meminfo
      - --collector.diskstats
    container_name: node_exporter
    hostname: nodeexporter
    mem_limit: 256m
    mem_reservation: 64m
    cpu_shares: 512
    security_opt:
      - no-new-privileges=true
    read_only: true
    user: 1026:100
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9100/
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  snmp-exporter:
    image: prom/snmp-exporter:latest
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    container_name: SNMP_Exporter
    hostname: snmp
    mem_limit: 256m
    mem_reservation: 64m
    cpu_shares: 512
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9116/ || exit 1
    volumes:
      - /volume1/docker/synology-monitoring/snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"   

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
      - '--docker_only=true'
      - "--housekeeping_interval=30s"
      - "--max_housekeeping_interval=35s"
      - "--global_housekeeping_interval=30s"
      - "--event_storage_event_limit=default=0"
      - "--event_storage_age_limit=default=0"
      - "--store_container_labels=false"
      - "--storage_duration=1m0s"
      - "--allow_dynamic_housekeeping=true"
    container_name: cadvisor
    hostname: cadvisor
    ports:
    - 8080:8080
    mem_limit: 256m
    mem_reservation: 64m
    cpu_shares: 512
    security_opt:
      - no-new-privileges=true
    read_only: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"    

  speedtest_exporter:
    image: ghcr.io/aaronmwelborn/speedtest_exporter:latest
    container_name: speedtest_exporter
    hostname: speedtest
    security_opt:
      - no-new-privileges=true
    read_only: true
    user: 1026:100
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true