version: '3'

networks:
  default:
    name: containers_bridge
    external: true  

services:
  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DATABASE_HOST: wp-mariadb
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
      WORDPRESS_FIRST_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_LAST_NAME: ${WORDPRESS_ADMIN_LASTNAME}
      WORDPRESS_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    volumes:
      - /volume1/docker/wordpress/data:/opt/bitnami/wordpress
    depends_on:
        - wp-mariadb
        - wp-redis
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${TRAEFIK_WORDPRESS}`)"
      - "traefik.http.routers.wordpress.service=wordpress"
      - "traefik.http.routers.wordpress.entrypoints=https"
      - "traefik.http.services.wordpress.loadbalancer.server.port=8080"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=mydnschallenge"
      - "traefik.http.services.wordpress.loadbalancer.passhostheader=true"
      - "traefik.http.routers.wordpress.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=false"      

  wp-mariadb:
    build:
      context: ./db
    restart: always
    container_name: wp-mariadb
    environment:
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_ADMIN_PASSWORD}
      MARIADB_CHARACTER_SET: utf8
      MARIADB_COLLATE: utf8_unicode_ci
    volumes:
      - /volume1/docker/wordpress/db:/bitnami/mariadb
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=false"         

  wp-redis:
    image: redis:latest
    restart: always
    container_name: wp-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=false"