version: '3'

networks:
  default:
    name: containers_bridge
    external: true  

services:
  mysitewordpress:
    image: bitnami/wordpress:6.3.1
    environment:
      WORDPRESS_DATABASE_HOST: mysitedb
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
      WORDPRESS_FIRST_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_LAST_NAME: ${WORDPRESS_ADMIN_LASTNAME}
      WORDPRESS_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    volumes:
      - /volume1/docker/wordpress/data:/var/www/html
    depends_on:
        - mysitedb
        - mysiteredis
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.http.routers.wordpressmysite.rule=Host(`${TRAEFIK_WORDPRESS}`)"
      - "traefik.http.routers.wordpressmysite.service=wordpress"
      - "traefik.http.routers.wordpressmysite.entrypoints=https"
      - "traefik.http.services.wordpressmysite.loadbalancer.server.port=8080"
      - "traefik.http.routers.wordpressmysite.tls=true"
      - "traefik.http.routers.wordpressmysite.tls.certresolver=mydnschallenge"
      - "traefik.http.services.wordpressmysite.loadbalancer.passhostheader=true"
      - "traefik.http.routers.wordpressmysite.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=false"      

  mysitedb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_ADMIN_PASSWORD}
    volumes:
      - /volume1/docker/mariadb/db:/var/lib/mysql
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=false"         

  mysiteredis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=false"       
    
  # Graphical interface to the database
  # Can be useful for debug  
  mysitephpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysitedb
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_ADMIN_PASSWORD}
    volumes:
     - /sessions
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=false"