version: '3'
services:
  gaps:
    container_name: gaps
    image: housewrecker/gaps:latest
    volumes:
      - /volume1/docker/gaps:/usr/data
    ports:
      - 8484:8484
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true