services:
  kometa:
    image: kometateam/kometa
    container_name: kometa
    environment:
      #- PMM_RUN=true
      - TZ=Europe/Kiev
    volumes:
      - ${VOLUME_DATA}/kometa/config:/config
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true