version: "3.8"
services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/docker/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
networks:
  default:
    name: containers_bridge
    external: true