version: "3.8"
services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/docker/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      # proxy settings    
      - "traefik.enable=true"    
      - "traefik.http.routers.jackett.entrypoints=https"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.jackett.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.jackett.tls.domains[0].sans=*.${LOCAL_DOMAIN}"
      # homepage integration      
      - homepage.group=Media
      - homepage.name=Jackett
      - homepage.icon=jackett.png
      - homepage.href=https://jackett.${LOCAL_DOMAIN}
      - homepage.description=Torrent indexer
      - homepage.widget.type=jackett
      - homepage.widget.url=http://jackett:9117
      # auto update docker      
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true