version: "3.8"
services:
  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    container_name: plex-meta-manager
    environment:
      # - PMM_RUN=true
      - TZ=Europe/Kiev
    volumes:
      - /volume1/config/plex-meta-manager/config:/config
    restart: unless-stopped
networks:
  default:
    name: containers_bridge
    external: true