services:
  plex-meta-manager:
    image: kometateam/kometa
    container_name: plex-meta-manager
    environment:
      #- PMM_RUN=true
      - TZ=Europe/Kiev
    volumes:
      - ${VOLUME_DATA}/plex-meta-manager/config:/config
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true