---
global:
  checkNewVersion: true
  sendAnonymousUsage: false
certificatesResolvers:
  mydnschallenge:
    acme:
      dnsChallenge:
        delayBeforeCheck: 10
        disablePropagationCheck: true
        provider: digitalocean
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      email: andrii@ivanskiy.com
      storage: ./letsencrypt/acme.json
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  ping:
    address: ":8082"
log:
  level: DEBUG  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /rules
    watch: true
api:
  insecure: true
  dashboard: true
ping:
  entryPoint: ping