scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: cloudkey
  scrape_interval: 10s
  static_configs:
  - targets:
    - cloudkey_monitor:80