version: '3.2'
services:
  cloudkey-monitor:
    image: ghcr.io/ivandriy/simple-uck2-plus-monitor:main
    container_name: cloudkey_monitor
    ports:
    - 9595:9595
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true