version: '3.2'
services:
  cloudkey-monitor:
    image: ghcr.io/ivandriy/simple-uck2-plus-monitor:main
    container_name: cloudkey_monitor
    restart: always
    healthcheck:
      test: curl --silent --fail http://localhost/health || exit 1
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 5s
    ports:
    - 9595:80
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      CloudKey__Url: ${CloudKey__Url}
      CloudKey__UserName: ${CloudKey__UserName}
      CloudKey__Password: ${CloudKey__Password}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
networks:
  default:
    name: containers_bridge
    external: true