services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      TZ: 'Europe/Kyiv'
    volumes:
      - ${VOLUME_DATA}/homeassistant:/config
      - ${VOLUME_DATA}/media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      # homepage integration
      - homepage.group=Smart home
      - homepage.name=Home Assistant
      - homepage.icon=home-assistant.png
      - homepage.href=https://ha.${LOCAL_DOMAIN}
      - homepage.description=Home Automations
      - homepage.widget.type=homeassistant
      - homepage.widget.url=${WIDGET_URL}
      - homepage.widget.key=${HA_TOKEN}
      - homepage.widget.custom[0].state=sensor.hue_motion_sensor_1_temperature
      - homepage.widget.custom[0].label=Температура вдома
      - homepage.widget.custom[1].state=sensor.hue_motion_sensor_1_illuminance
      - homepage.widget.custom[1].label=Освітлення
      # auto update docker
      - "com.centurylinklabs.watchtower.monitor-only=true"