version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      TZ: 'Europe/Kyiv'
    volumes:
      - /volume1/docker/homeassistant:/config
      - /volume1/docker/media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"