version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      TZ: 'Europe/Kyiv'
    volumes:
      - /volume1/docker/homeassistant:/config
      - /volume1/docker/media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      macvlan1:
        ipv4_address: 192.168.1.15
      containers_bridge:    
    labels:    
      - "com.centurylinklabs.watchtower.monitor-only=true"
networks:
  containers_bridge:
    external: true
  macvlan1:
    name: macvlan1
    driver: macvlan
    driver_opts:
      parent: ovs_bond0
    ipam:
      config:
        - subnet: 192.168.1.1/24
          ip_range: 192.168.1.10/31
          gateway: 192.168.1.1