version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      TZ: 'Europe/Kyiv'
    volumes:
      - /volume1/docker/homeassistant:/config
      - /volume1/docker/media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ha-local.entrypoints=https"
      - "traefik.http.routers.ha-local.rule=Host(`${TRAEFIK_HA_LOCAL}`)"
      - "traefik.http.services.ha-local.loadbalancer.server.url=http://192.168.1.254"
      - "traefik.http.services.ha-local.loadbalancer.server.port=8123"
      - "traefik.http.services.ha-local.loadbalancer.passhostheader=true"   
      - "traefik.http.routers.ha-local.tls=true"
      - "traefik.http.routers.ha-local.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.ha-local.tls.domains[0].main=${TRAEFIK_LOCAL_DOMAIN}"
      - "traefik.http.routers.ha-local.tls.domains[0].sans=*.${TRAEFIK_LOCAL_DOMAIN}"     
      - "com.centurylinklabs.watchtower.monitor-only=true"