version: "3.7"
services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Check for updates every couple hours: (3h * 60m * 60s)
    command: --interval 10800
    environment:
      - "TZ=Europe/Kiev"
      - "WATCHTOWER_LABEL_ENABLE=true"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_INCLUDE_RESTARTING=true"
      - "WATCHTOWER_MONITOR_ONLY=true"
      - "WATCHTOWER_NOTIFICATIONS=email"
      - "WATCHTOWER_NOTIFICATION_EMAIL_FROM=ivandriy@gmail.com"
      - "WATCHTOWER_NOTIFICATION_EMAIL_TO=andrii@ivanskiy.com"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=[Watchtower]"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587"
      - "WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2"
networks:
  default:
    name: containers_bridge
    external: true