version: "3.7"
services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Check for updates every couple hours: (3h * 60m * 60s)
    command: --interval 10800
    env_file:
      - stack.env
networks:
  default:
    name: containers_bridge
    external: true