version: '3'
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - ${VOLUME_DATA}/heimdall/config:/config
    ports:
      - 8088:80
      - 8089:443
    restart: unless-stopped
    labels:
      # local heimdall access
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall-local.entrypoints=https"
      - "traefik.http.routers.heimdall-local.rule=Host(`heimdall.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.heimdall-local.tls=true"
      - "traefik.http.routers.heimdall-local.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.heimdall-local.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.heimdall-local.tls.domains[0].sans=*.${LOCAL_DOMAIN}" 
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true