version: '3'

services:
 webserver:
    image: 'httpd:2.4'
    container_name: webserver
    restart: unless-stopped
    volumes:
      - /volume1/config/webserver/data:/usr/local/apache2/htdocs/
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`home.ivanskiy.com`)"
      - "traefik.http.routers.webserver.entrypoints=https"
      - "traefik.http.routers.webserver.tls=true"
      - "traefik.http.routers.webserver.tls.certresolver=mydnschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    name: containers_bridge
    external: true