version: "3.8"
services:
  Sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/config/sonarr:/config
      - /volume1/Data:/Data
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"    
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.sonarr.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.sonarr.tls.domains[0].sans=*.${LOCAL_DOMAIN}"    
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true