version: "3.8"
services:
  Sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/config/sonarr:/config
      - /volume1/Data:/Data
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      # proxy settings    
      - "traefik.enable=true"    
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.sonarr.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.sonarr.tls.domains[0].sans=*.${LOCAL_DOMAIN}"
      # homepage integration
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=https://sonarr.${LOCAL_DOMAIN}
      - homepage.description=Series manager
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://lidarr:8989
      - homepage.widget.key=${SONARR_API_KEY}
      - homepage.widget.enableQueue=true   
      # auto update docker          
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true