services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /volume1/docker/zigbee2mqtt:/app/data
    ports:
      - 8888:8080
    environment:
      - TZ=Europe/Kiev
    privileged: true
    depends_on:
       - mosquitto
    labels:            
      # homepage integration
      - homepage.group=Smart home
      - homepage.name=Zigbee2MQTT
      - homepage.icon=zigbee2mqtt.png
      - homepage.href=https://z2mqtt.${LOCAL_DOMAIN}
      - homepage.description=Zigbee to MQTT
      # auto update docker        
      - "com.centurylinklabs.watchtower.monitor-only=true"

  mosquitto:
    image: eclipse-mosquitto:1.6
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    privileged: true     
    volumes:
      - /volume1/docker/mosquitto:/etc/mosquitto
    labels:            
      # auto update docker        
      - "com.centurylinklabs.watchtower.monitor-only=true"

networks:
  default:
    name: containers_bridge
    external: true