services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:${Z2M_VERSION}
    restart: unless-stopped
    volumes:
      - ${VOLUME_DATA}/zigbee2mqtt:/app/data
    ports:
      - ${Z2M_HTTP_PORT}:8080
    environment:
      - TZ=Europe/Kiev
    privileged: true
    depends_on:
       - mosquitto
    labels:
      # homepage integration
      - homepage.group=Smart home
      - homepage.name=Zigbee2MQTT
      - homepage.icon=zigbee2mqtt.png
      - homepage.href=https://z2mqtt.${LOCAL_DOMAIN}
      - homepage.description=Zigbee to MQTT
      # auto update docker
      - "com.centurylinklabs.watchtower.monitor-only=true"

  mosquitto:
    image: eclipse-mosquitto:${MQTT_VERSION}
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - ${MQTT_PORT1}:1883
      - ${MQTT_PORT2}:9001
    privileged: true
    volumes:
      - ${VOLUME_DATA}/mosquitto:/etc/mosquitto
    labels:
      # auto update docker
      - "com.centurylinklabs.watchtower.monitor-only=true"

networks:
  default:
    name: containers_bridge
    external: true