version: "3.7"
services:
  photostructure:
    image: photostructure/server:stable
    container_name: photostructure
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - type: bind
        source: /volume1/config/photostructure/library
        target: /ps/library
      - type: bind
        source: /volume1/config/photostructure/tmp
        target: /ps/tmp
      - type: bind
        source: /volume1/config/photostructure/config
        target: /ps/config
      - type: bind
        source: /volume1/config/photostructure/logs
        target: /ps/logs
      - type: bind
        source: /volume1/Data/Dropbox/Photos
        target: /var/photos
      - type: bind
        source: "/volume1/Data/Dropbox/Camera Uploads"
        target: /var/photos-iphone

    ports:
      - 1787:1787/tcp

    environment:
      - "TZ=Europe/Kiev"
      - "PUID=1026"
      - "PGID=100"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true