services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral
      - /dev/dri:/dev/dri # For Intel QuickSync
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_DATA}/frigate/config:/config
      - ${VOLUME_DATA}/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    labels:
      # auto update docker
      - "com.centurylinklabs.watchtower.monitor-only=true"

networks:
  default:
    name: containers_bridge
    external: true