---
version: "3.7"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
      - WEBUI_PORT=6004
    volumes:
      - /volume1/config/qbittorrent:/config
      - /volume1/Data/Downloads:/Data/Downloads
    ports:
      - 6004:6004
      - 6881:6881
      - 6881:6881/udp 
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true