version: "3.8"
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/config/lidarr:/config
      - /volume1/Data:/Data
    ports:
      - 8686:8686
    restart: unless-stopped
    labels:
      - "traefik.enable=true"    
      - "traefik.http.routers.lidarr.entrypoints=https"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.lidarr.tls=true"
      - "traefik.http.routers.lidarr.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.lidarr.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.lidarr.tls.domains[0].sans=*.${LOCAL_DOMAIN}"
      - "com.centurylinklabs.watchtower.enable=true"
      # homepage integration
      - homepage.group=Media
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=https://lidarr.local.ivanskiy.com/
      - homepage.description=Music manager
networks:
  default:
    name: containers_bridge
    external: true