version: "3.8"
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/docker/lidarr:/config
      - /volume1/Data/Downloads/Music:/downloads
      - /volume1/Data/Music:/music
    ports:
      - 8686:8686
    restart: unless-stopped
networks:
  default:
    name: containers_bridge
    external: true