version: "3.8"
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/config/lidarr:/config
      - /volume1/Data:/Data
    ports:
      - 8686:8686
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true