version: '3.8'
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - VERSION=latest
      - TZ=Europe/Kiev
    volumes:
      - '/volume1/config/plex:/config'
      - '/volume1/Data/Media:/data/media:rw'
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"