version: '3.8'
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - VERSION=latest
      - TZ=Europe/Kiev
    volumes:
      - '/volume1/config/plex:/config'
      - '/volume1/Data/Media:/data/media:rw'
    restart: unless-stopped
    labels:
      # homepage integration
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=http://192.168.1.254:32400/web/index.html
      - homepage.description=Media player
      - homepage.widget.type=plex
      - homepage.widget.url=http://192.168.1.254:32400
      - homepage.widget.key=${PLEX_TOKEN}
      # auto update docker    
      - "com.centurylinklabs.watchtower.enable=false"