services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - VERSION=latest
      - TZ=Europe/Kiev
    volumes:
      - '${VOLUME_DATA}/plex:/config'
      - '${MEDIA_DATA}:/data/media'
    restart: unless-stopped
    labels:
      # homepage integration
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=${HOME_PAGE_URL}/web/index.html
      - homepage.description=Media player
      - homepage.widget.type=plex
      - homepage.widget.url=${HOME_PAGE_URL}
      - homepage.widget.key=${PLEX_TOKEN}
      # auto update docker
      - "com.centurylinklabs.watchtower.enable=false"