http:
  routers:
    ha-local:
      entryPoints:
        - "https"
      service: ha-local
      rule: Host(`{{ env "TRAEFIK_HA_LOCAL" }}`)
      tls:
        certResolver: mydnschallenge
        domains:
          - main: '{{ env "TRAEFIK_LOCAL_DOMAIN" }}'
            sans:
              - '*.{{ env "TRAEFIK_LOCAL_DOMAIN" }}'
  services:
    ha-local:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: {{ expandenv "http://$HA_HOST" }}