http:
  routers:
    homeassistant:
      entryPoints:
        - "https"
      service: homeassistant
      rule: Host(`ha.{{ env "LOCAL_DOMAIN" }}`)
      tls:
        certResolver: mydnschallenge
        domains:
          - main: '{{ env "LOCAL_DOMAIN" }}'
            sans:
              - '*.{{ env "LOCAL_DOMAIN" }}'
  services:
    homeassistant:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: {{ expandenv "http://$HA_HOST" }}