http:
  middlewares:
    whitelist:
      ipWhiteList:
        sourceRange:
          - "0.0.0.0/0"
          # Private IP range use by docker, enable to enable services access through VPN
          - "172.20.0.0/16"