version: "3.8"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/config/radarr:/config
      - /volume1/Data:/Data
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      # proxy settings
      - "traefik.enable=true"    
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.radarr.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.radarr.tls.domains[0].sans=*.${LOCAL_DOMAIN}"
      # homepage integration
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=https://radarr.${LOCAL_DOMAIN}
      - homepage.description=Movie manager
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_API_KEY}
      # auto update docker          
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true