version: "3.8"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Kiev
    volumes:
      - /volume1/config/radarr:/config
      - /volume1/Data:/Data
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"    
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.radarr.tls.domains[0].main=${LOCAL_DOMAIN}"
      - "traefik.http.routers.radarr.tls.domains[0].sans=*.${LOCAL_DOMAIN}"    
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    name: containers_bridge
    external: true